spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Client-Id
            clientSecret: Client-Secret
            scope:
              - user:email
              - read:user

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/writer
    username: writer
    password: -123writer
    hikari:
      maximum-pool-size: 30
    configuration:
      auto-commit: false
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy





